import { ArtisanProfile, CraftCategory, ProductItem } from "./types";

export const initialArtisanProfile: ArtisanProfile = {
  id: "ART-808",
  name: "Ramesh Swarnakar",
  craftSpecialtyEn: "Terracotta & Heritage Pottery",
  craftSpecialtyHi: "टेराकोटा और पारंपरिक मिट्टी के बर्तन",
  locationEn: "Bankura, West Bengal",
  locationHi: "बांकुड़ा, पश्चिम बंगाल",
  experienceYears: 22,
  verificationBadge: "Pahchan Artisan Card #WB-808",
  avatar: "/ramesh.png",
  totalProducts: 16,
  totalEarningsInr: 148500,
};

export const craftCategories: CraftCategory[] = [
  {
    id: "terracotta",
    nameEn: "Terracotta & Clay",
    nameHi: "टेराकोटा और मिट्टी",
    iconName: "Flame",
    descriptionEn: "Traditional baked clay horses, pots, figurines & tiles",
    descriptionHi: "पारंपरिक मिट्टी के घोड़े, बर्तन, मूर्तियां और टाइलें",
    color: "bg-orange-500/10 text-orange-700 border-orange-200",
    sampleImage: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "pottery",
    nameEn: "Blue Pottery & Ceramics",
    nameHi: "ब्लू पॉटरी और सिरेमिक",
    iconName: "Sparkles",
    descriptionEn: "Quartz-glazed Jaipur blue pottery, vases & tableware",
    descriptionHi: "जयपुर की प्रसिद्ध ब्लू पॉटरी, फूलदान और सजावटी बर्तन",
    color: "bg-sky-500/10 text-sky-700 border-sky-200",
    sampleImage: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "brass",
    nameEn: "Dhokra & Brass Craft",
    nameHi: "ढोकरा और पीतल कला",
    iconName: "Hammer",
    descriptionEn: "Lost-wax bell metal casting, brass lamps & tribal art",
    descriptionHi: "पारंपरिक पीतल के दिए, घंटियां और ढोकरा जनजातीय कला",
    color: "bg-amber-500/10 text-amber-700 border-amber-200",
    sampleImage: "https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "woodwork",
    nameEn: "Carved Woodwork",
    nameHi: "लकड़ी पर नक्काशी",
    iconName: "Trees",
    descriptionEn: "Saharanpur carved teakwood panels, boxes & toys",
    descriptionHi: "सहारनपुर की सागौन की लकड़ी की नक्काशीदार डिब्बे व खिलौने",
    color: "bg-emerald-500/10 text-emerald-700 border-emerald-200",
    sampleImage: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "textiles",
    nameEn: "Handloom Textiles",
    nameHi: "हथकरघा वस्त्र व साड़ियां",
    iconName: "Shirt",
    descriptionEn: "Handwoven Ikat, Chanderi, Pashmina & Zardozi embroidery",
    descriptionHi: "हाथ से बुनी इकत, चंदेरी, पश्मीना व ज़रदोज़ी कढ़ाई",
    color: "bg-rose-500/10 text-rose-700 border-rose-200",
    sampleImage: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "paintings",
    nameEn: "Folk Paintings",
    nameHi: "लोक चित्रकला (मधुबनी/वरली)",
    iconName: "Palette",
    descriptionEn: "Madhubani, Warli, Pattachitra & Gond folk wall art",
    descriptionHi: "मधुबनी, वरली, पट्टचित्र और गोंड लोक कला पेंटिंग",
    color: "bg-purple-500/10 text-purple-700 border-purple-200",
    sampleImage: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=400&q=80",
  },
];

export const initialProducts: ProductItem[] = [
  // ─── 1. Terracotta Horse ───────────────────────────────────────────
  {
    id: "PRD-101",
    titleEn: "Heritage Bankura Terracotta Horse (35cm)",
    titleHi: "पारंपरिक बांकुड़ा टेराकोटा घोड़ा (35 सेमी)",
    category: "terracotta",
    categoryNameEn: "Terracotta & Clay",
    categoryNameHi: "टेराकोटा और मिट्टी",
    craftStoryEn: "Handcrafted using alluvial riverbank clay from Bankura. Molded by hand wheel and baked in a natural firewood kiln for 14 hours.",
    craftStoryHi: "बांकुड़ा की नदी की मिट्टी से हाथ से बनाया गया। 14 घंटे प्राकृतिक लकड़ी के भट्ठे में पकाया गया।",
    materialsEn: ["Alluvial River Clay", "Natural Earth Ochre Pigment"],
    materialsHi: ["नदी की प्राकृतिक मिट्टी", "प्राकृतिक गेरू रंग"],
    dimensions: "35cm x 15cm x 10cm",
    weight: "1.4 kg",
    image: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 280,
      laborHours: 14,
      laborHourlyRate: 90,
      complexityGrade: 4,
      artisanExperienceYears: 22,
      demandIndex: 1.25,
      minimumFairPrice: 1540,
      suggestedB2BPrice: 2250,
    },
    status: "published",
    createdAt: "2026-09-01",
    qrCodeId: "QR-KGX-101",
    voiceTranscriptEn: "This is a 35cm high Bankura terracotta horse. It took me 14 hours of work and 280 rupees of raw clay and wood for firing.",
    voiceTranscriptHi: "यह 35 सेमी ऊँचा बांकुड़ा का मिट्टी का घोड़ा है। इसे बनाने में 14 घंटे की मेहनत लगी और 280 रुपये का सामान लगा।",
  },

  // ─── 2. Blue Pottery Vase ──────────────────────────────────────────
  {
    id: "PRD-102",
    titleEn: "Jaipur Floral Blue Pottery Vase",
    titleHi: "जयपुर फूलदार नीला सिरेमिक फूलदान",
    category: "pottery",
    categoryNameEn: "Blue Pottery",
    categoryNameHi: "ब्लू पॉटरी",
    craftStoryEn: "Authentic quartz-based Jaipur blue pottery vase decorated with cobalt oxides and hand-painted traditional Mughal floral motifs.",
    craftStoryHi: "क्वार्ट्ज और कोबाल्ट ऑक्साइड से निर्मित प्रामाणिक जयपुर ब्लू पॉटरी फूलदान।",
    materialsEn: ["Quartz Powder", "Glass Frit", "Cobalt Oxide Dye"],
    materialsHi: ["क्वार्ट्ज पाउडर", "कांच का चूर्ण", "कोबाल्ट रंग"],
    dimensions: "28cm x 12cm",
    weight: "0.9 kg",
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 350,
      laborHours: 16,
      laborHourlyRate: 100,
      complexityGrade: 5,
      artisanExperienceYears: 18,
      demandIndex: 1.3,
      minimumFairPrice: 1950,
      suggestedB2BPrice: 2800,
    },
    status: "published",
    createdAt: "2026-08-28",
    qrCodeId: "QR-KGX-102",
  },

  // ─── 3. Dhokra Brass Lamp ─────────────────────────────────────────
  {
    id: "PRD-103",
    titleEn: "Dhokra Bell Metal Peacock Lamp",
    titleHi: "ढोकरा पीतल मयूर दीया",
    category: "brass",
    categoryNameEn: "Dhokra Craft",
    categoryNameHi: "ढोकरा कला",
    craftStoryEn: "Traditional lost-wax brass casting crafted by tribal artisans in Bastar. Features intricate hand-spun wax wirework detailing.",
    craftStoryHi: "बस्तर के जनजातीय कारीगरों द्वारा प्राचीन लॉस्ट-वैक्स विधि से तैयार किया गया पीतल का सजावटी दीया।",
    materialsEn: ["Recycled Brass", "Bee Wax", "Clay Core"],
    materialsHi: ["पीतल धातु", "मोम की तार", "मिट्टी"],
    dimensions: "20cm x 15cm",
    weight: "1.1 kg",
    image: "https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 450,
      laborHours: 18,
      laborHourlyRate: 110,
      complexityGrade: 5,
      artisanExperienceYears: 20,
      demandIndex: 1.35,
      minimumFairPrice: 2430,
      suggestedB2BPrice: 3400,
    },
    status: "published",
    createdAt: "2026-08-25",
    qrCodeId: "QR-KGX-103",
  },

  // ─── 4. Teak Jewelry Box ──────────────────────────────────────────
  {
    id: "PRD-104",
    titleEn: "Hand-Carved Saharanpur Teak Jewelry Box",
    titleHi: "सहारनपुर नक्काशीदार लकड़ी का गहना डिब्बा",
    category: "woodwork",
    categoryNameEn: "Carved Woodwork",
    categoryNameHi: "लकड़ी की नक्काशी",
    craftStoryEn: "Solid seasoned teakwood jewelry box intricately carved with traditional leaf brass inlay work.",
    craftStoryHi: "ठोस सागौन की लकड़ी से बना गहनों का डिब्बा, जिस पर पीतल के तारों और नक्काशी की सजावट की गई है।",
    materialsEn: ["Seasoned Teakwood", "Brass Wire Inlay"],
    materialsHi: ["सागौन की लकड़ी", "पीतल का काम"],
    dimensions: "22cm x 14cm x 8cm",
    weight: "0.8 kg",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 320,
      laborHours: 10,
      laborHourlyRate: 90,
      complexityGrade: 3,
      artisanExperienceYears: 15,
      demandIndex: 1.15,
      minimumFairPrice: 1220,
      suggestedB2BPrice: 1850,
    },
    status: "draft",
    createdAt: "2026-09-02",
    qrCodeId: "QR-KGX-104",
  },

  // ─── 5. Madhubani Painting ────────────────────────────────────────
  {
    id: "PRD-105",
    titleEn: "Madhubani Fish Motif Painting (A3)",
    titleHi: "मधुबनी मछली चित्रकला (A3 आकार)",
    category: "paintings",
    categoryNameEn: "Folk Paintings",
    categoryNameHi: "लोक चित्रकला",
    craftStoryEn: "Hand-painted Madhubani art from Bihar using natural dyes on handmade paper. Features the iconic fish motif symbolizing fertility and prosperity.",
    craftStoryHi: "बिहार की पारंपरिक मधुबनी चित्रकला। हस्तनिर्मित कागज पर प्राकृतिक रंगों से बनाई गई मछली की आकृति जो समृद्धि का प्रतीक है।",
    materialsEn: ["Handmade Paper", "Natural Dyes", "Bamboo Pen"],
    materialsHi: ["हस्तनिर्मित कागज", "प्राकृतिक रंग", "बाँस की कलम"],
    dimensions: "42cm x 30cm",
    weight: "0.15 kg",
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 120,
      laborHours: 8,
      laborHourlyRate: 80,
      complexityGrade: 4,
      artisanExperienceYears: 12,
      demandIndex: 1.2,
      minimumFairPrice: 860,
      suggestedB2BPrice: 1400,
    },
    status: "published",
    createdAt: "2026-09-03",
    qrCodeId: "QR-KGX-105",
  },

  // ─── 6. Chanderi Silk Dupatta ─────────────────────────────────────
  {
    id: "PRD-106",
    titleEn: "Chanderi Silk Zari Dupatta",
    titleHi: "चंदेरी सिल्क ज़री दुपट्टा",
    category: "textiles",
    categoryNameEn: "Handloom Textiles",
    categoryNameHi: "हथकरघा वस्त्र",
    craftStoryEn: "Handwoven on a traditional pit loom in Chanderi, Madhya Pradesh. Pure silk warp with zari border using real silver-coated copper thread.",
    craftStoryHi: "मध्य प्रदेश के चंदेरी में पारंपरिक गड्ढे वाले करघे पर हाथ से बुना गया। शुद्ध रेशम और असली चाँदी के ज़री बॉर्डर के साथ।",
    materialsEn: ["Pure Silk", "Silver-Coated Copper Zari", "Cotton Weft"],
    materialsHi: ["शुद्ध रेशम", "चाँदी लपेटा तांबा ज़री", "सूती ताना"],
    dimensions: "250cm x 90cm",
    weight: "0.2 kg",
    image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 800,
      laborHours: 24,
      laborHourlyRate: 85,
      complexityGrade: 5,
      artisanExperienceYears: 25,
      demandIndex: 1.4,
      minimumFairPrice: 2840,
      suggestedB2BPrice: 4200,
    },
    status: "published",
    createdAt: "2026-08-20",
    qrCodeId: "QR-KGX-106",
  },

  // ─── 7. Terracotta Wall Plate ─────────────────────────────────────
  {
    id: "PRD-107",
    titleEn: "Terracotta Decorative Wall Plate (30cm)",
    titleHi: "टेराकोटा सजावटी दीवार प्लेट (30 सेमी)",
    category: "terracotta",
    categoryNameEn: "Terracotta & Clay",
    categoryNameHi: "टेराकोटा और मिट्टी",
    craftStoryEn: "Hand-pressed decorative wall plate with floral relief work. Fired in a traditional pit kiln and finished with natural lacquer.",
    craftStoryHi: "फूलों की उभरी नक्काशी वाली हाथ से दबाई गई सजावटी प्लेट। पारंपरिक भट्ठे में पकाई और प्राकृतिक लाख से चमकाई गई।",
    materialsEn: ["Red Clay", "Natural Lacquer", "Ochre Wash"],
    materialsHi: ["लाल मिट्टी", "प्राकृतिक लाख", "गेरू धुलाई"],
    dimensions: "30cm diameter x 3cm",
    weight: "0.7 kg",
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 150,
      laborHours: 6,
      laborHourlyRate: 80,
      complexityGrade: 3,
      artisanExperienceYears: 22,
      demandIndex: 1.1,
      minimumFairPrice: 680,
      suggestedB2BPrice: 1100,
    },
    status: "published",
    createdAt: "2026-09-05",
    qrCodeId: "QR-KGX-107",
  },

  // ─── 8. Brass Diya Set ────────────────────────────────────────────
  {
    id: "PRD-108",
    titleEn: "Traditional Brass Diya Set (5 Pieces)",
    titleHi: "पारंपरिक पीतल दीया सेट (5 का सेट)",
    category: "brass",
    categoryNameEn: "Brass Craft",
    categoryNameHi: "पीतल कला",
    craftStoryEn: "Set of five hand-cast brass oil lamps in graduated sizes. Each piece is individually molded and hand-polished to a mirror finish.",
    craftStoryHi: "पाँच अलग-अलग आकार के हाथ से ढाले गए पीतल के तेल के दीयों का सेट। हर दीया अलग से ढाला और हाथ से चमकाया गया है।",
    materialsEn: ["Solid Brass", "Cotton Wicks"],
    materialsHi: ["ठोस पीतल", "सूती बत्ती"],
    dimensions: "5cm to 12cm diameter",
    weight: "1.8 kg",
    image: "https://images.unsplash.com/photo-1614088685112-0a760b71a3c8?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 600,
      laborHours: 12,
      laborHourlyRate: 100,
      complexityGrade: 3,
      artisanExperienceYears: 18,
      demandIndex: 1.45,
      minimumFairPrice: 1800,
      suggestedB2BPrice: 2650,
    },
    status: "published",
    createdAt: "2026-08-15",
    qrCodeId: "QR-KGX-108",
  },

  // ─── 9. Warli Art Canvas ──────────────────────────────────────────
  {
    id: "PRD-109",
    titleEn: "Warli Village Life Canvas Painting",
    titleHi: "वरली ग्रामीण जीवन कैनवास पेंटिंग",
    category: "paintings",
    categoryNameEn: "Folk Paintings",
    categoryNameHi: "लोक चित्रकला",
    craftStoryEn: "Hand-painted Warli tribal art on canvas depicting village life, harvest dance, and nature. Created by Warli artists from Maharashtra using rice paste on a mud-brown base.",
    craftStoryHi: "महाराष्ट्र के वरली आदिवासी कलाकारों द्वारा कैनवास पर बनाई गई चित्रकला। गाँव का जीवन, फसल कटाई का नृत्य और प्रकृति का चित्रण।",
    materialsEn: ["Canvas", "Rice Paste", "Natural Brown Pigment"],
    materialsHi: ["कैनवास", "चावल का लेप", "प्राकृतिक भूरा रंग"],
    dimensions: "60cm x 45cm",
    weight: "0.4 kg",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 200,
      laborHours: 10,
      laborHourlyRate: 90,
      complexityGrade: 4,
      artisanExperienceYears: 14,
      demandIndex: 1.25,
      minimumFairPrice: 1100,
      suggestedB2BPrice: 1800,
    },
    status: "published",
    createdAt: "2026-09-04",
    qrCodeId: "QR-KGX-109",
  },

  // ─── 10. Handwoven Jute Bag ───────────────────────────────────────
  {
    id: "PRD-110",
    titleEn: "Handwoven Jute Tote Bag with Kantha Stitch",
    titleHi: "कांथा सिलाई वाला जूट का हस्तनिर्मित थैला",
    category: "textiles",
    categoryNameEn: "Handloom Textiles",
    categoryNameHi: "हथकरघा वस्त्र",
    craftStoryEn: "Eco-friendly handwoven jute tote bag adorned with running Kantha stitch embroidery from Bengal. Sturdy cotton lining with internal pockets.",
    craftStoryHi: "बंगाल की कांथा कढ़ाई से सजा पर्यावरण-अनुकूल जूट का थैला। मजबूत सूती अस्तर और अंदर जेबें।",
    materialsEn: ["Natural Jute", "Cotton Thread", "Cotton Lining"],
    materialsHi: ["प्राकृतिक जूट", "सूती धागा", "सूती अस्तर"],
    dimensions: "40cm x 35cm x 12cm",
    weight: "0.35 kg",
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 180,
      laborHours: 8,
      laborHourlyRate: 70,
      complexityGrade: 3,
      artisanExperienceYears: 10,
      demandIndex: 1.3,
      minimumFairPrice: 750,
      suggestedB2BPrice: 1200,
    },
    status: "published",
    createdAt: "2026-09-06",
    qrCodeId: "QR-KGX-110",
  },

  // ─── 11. Marble Inlay Coaster Set ─────────────────────────────────
  {
    id: "PRD-111",
    titleEn: "Agra Marble Inlay Coaster Set (4 Pieces)",
    titleHi: "आगरा संगमरमर पच्चीकारी कोस्टर सेट (4 का सेट)",
    category: "woodwork",
    categoryNameEn: "Stone Inlay",
    categoryNameHi: "पत्थर पच्चीकारी",
    craftStoryEn: "White Makrana marble coasters with semi-precious stone inlay work inspired by Taj Mahal craftsmanship. Each piece hand-cut and individually fitted.",
    craftStoryHi: "ताज महल की कारीगरी से प्रेरित सफेद मकराना संगमरमर के कोस्टर। हर टुकड़ा हाथ से काटा और अलग-अलग जड़ा गया है।",
    materialsEn: ["Makrana Marble", "Malachite", "Lapis Lazuli", "Mother of Pearl"],
    materialsHi: ["मकराना संगमरमर", "मैलाकाइट", "लाजवर्द", "सीप"],
    dimensions: "10cm x 10cm each",
    weight: "0.6 kg",
    image: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 500,
      laborHours: 14,
      laborHourlyRate: 120,
      complexityGrade: 5,
      artisanExperienceYears: 20,
      demandIndex: 1.35,
      minimumFairPrice: 2180,
      suggestedB2BPrice: 3200,
    },
    status: "published",
    createdAt: "2026-08-22",
    qrCodeId: "QR-KGX-111",
  },

  // ─── 12. Bamboo Flower Basket ─────────────────────────────────────
  {
    id: "PRD-112",
    titleEn: "Handwoven Bamboo Flower Basket",
    titleHi: "हाथ से बुनी बाँस की फूलों की टोकरी",
    category: "woodwork",
    categoryNameEn: "Bamboo Craft",
    categoryNameHi: "बाँस शिल्प",
    craftStoryEn: "Intricately woven bamboo basket from Assam using split bamboo strips. Perfect for dried flowers or as a decorative centerpiece.",
    craftStoryHi: "असम की पारंपरिक बाँस बुनाई। बाँस की पतली पट्टियों से बनी सुंदर टोकरी। सूखे फूलों या सजावट के लिए उपयुक्त।",
    materialsEn: ["Split Bamboo", "Natural Cane Binding"],
    materialsHi: ["कटा बाँस", "प्राकृतिक बेंत बंधन"],
    dimensions: "25cm x 20cm x 18cm",
    weight: "0.3 kg",
    image: "https://images.unsplash.com/photo-1595351298020-038700609878?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 80,
      laborHours: 6,
      laborHourlyRate: 60,
      complexityGrade: 3,
      artisanExperienceYears: 8,
      demandIndex: 1.15,
      minimumFairPrice: 450,
      suggestedB2BPrice: 750,
    },
    status: "draft",
    createdAt: "2026-09-08",
    qrCodeId: "QR-KGX-112",
  },

  // ─── 13. Block Print Table Runner ─────────────────────────────────
  {
    id: "PRD-113",
    titleEn: "Rajasthani Block Print Table Runner",
    titleHi: "राजस्थानी ब्लॉक प्रिंट टेबल रनर",
    category: "textiles",
    categoryNameEn: "Handloom Textiles",
    categoryNameHi: "हथकरघा वस्त्र",
    craftStoryEn: "Hand-block printed cotton table runner from Sanganer, Jaipur. Traditional floral pattern using hand-carved wooden blocks and natural indigo dye.",
    craftStoryHi: "जयपुर के सांगानेर से हाथ से ब्लॉक प्रिंट किया गया सूती टेबल रनर। लकड़ी के हाथ से बने ब्लॉक और प्राकृतिक नील रंग से छपाई।",
    materialsEn: ["Cotton Fabric", "Natural Indigo Dye", "Wooden Block"],
    materialsHi: ["सूती कपड़ा", "प्राकृतिक नील", "लकड़ी का ब्लॉक"],
    dimensions: "180cm x 35cm",
    weight: "0.25 kg",
    image: "https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 150,
      laborHours: 5,
      laborHourlyRate: 75,
      complexityGrade: 3,
      artisanExperienceYears: 12,
      demandIndex: 1.2,
      minimumFairPrice: 550,
      suggestedB2BPrice: 900,
    },
    status: "published",
    createdAt: "2026-09-07",
    qrCodeId: "QR-KGX-113",
  },

  // ─── 14. Pattachitra Painting ─────────────────────────────────────
  {
    id: "PRD-114",
    titleEn: "Odisha Pattachitra Krishna Leela Scroll",
    titleHi: "ओडिशा पट्टचित्र कृष्ण लीला चित्र",
    category: "paintings",
    categoryNameEn: "Folk Paintings",
    categoryNameHi: "लोक चित्रकला",
    craftStoryEn: "Intricate Pattachitra scroll painting from Raghurajpur, Odisha depicting Krishna Leela. Painted on treated cloth using natural mineral and vegetable colors.",
    craftStoryHi: "ओडिशा के रघुराजपुर से पारंपरिक पट्टचित्र। कपड़े पर प्राकृतिक खनिज और वनस्पति रंगों से कृष्ण लीला का चित्रण।",
    materialsEn: ["Treated Cloth", "Natural Mineral Colors", "Tamarind Seed Gum"],
    materialsHi: ["प्रसंस्कृत कपड़ा", "प्राकृतिक खनिज रंग", "इमली के बीज का गोंद"],
    dimensions: "45cm x 30cm",
    weight: "0.2 kg",
    image: "https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 250,
      laborHours: 20,
      laborHourlyRate: 95,
      complexityGrade: 5,
      artisanExperienceYears: 16,
      demandIndex: 1.3,
      minimumFairPrice: 2150,
      suggestedB2BPrice: 3100,
    },
    status: "published",
    createdAt: "2026-08-18",
    qrCodeId: "QR-KGX-114",
  },

  // ─── 15. Terracotta Planter Set ───────────────────────────────────
  {
    id: "PRD-115",
    titleEn: "Hand-Painted Terracotta Planter Set (3 Pieces)",
    titleHi: "हाथ से पेंट किया टेराकोटा गमला सेट (3 का सेट)",
    category: "terracotta",
    categoryNameEn: "Terracotta & Clay",
    categoryNameHi: "टेराकोटा और मिट्टी",
    craftStoryEn: "Set of three hand-thrown terracotta planters with hand-painted geometric tribal patterns. Kiln-fired with drainage holes for live plants.",
    craftStoryHi: "तीन हाथ से बने टेराकोटा गमलों का सेट। जनजातीय ज्यामितीय पैटर्न से हाथ से पेंट किए गए। भट्ठे में पके और पानी निकलने के छेद वाले।",
    materialsEn: ["Natural Clay", "Acrylic Paint", "Natural Sealant"],
    materialsHi: ["प्राकृतिक मिट्टी", "ऐक्रेलिक रंग", "प्राकृतिक सीलेंट"],
    dimensions: "12cm, 15cm, 18cm diameter",
    weight: "2.1 kg",
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 200,
      laborHours: 8,
      laborHourlyRate: 80,
      complexityGrade: 3,
      artisanExperienceYears: 22,
      demandIndex: 1.2,
      minimumFairPrice: 860,
      suggestedB2BPrice: 1350,
    },
    status: "draft",
    createdAt: "2026-09-10",
    qrCodeId: "QR-KGX-115",
  },

  // ─── 16. Zardozi Clutch Purse ─────────────────────────────────────
  {
    id: "PRD-116",
    titleEn: "Zardozi Embroidered Silk Clutch Purse",
    titleHi: "ज़रदोज़ी कढ़ाई वाला रेशमी क्लच पर्स",
    category: "textiles",
    categoryNameEn: "Handloom Textiles",
    categoryNameHi: "हथकरघा वस्त्र",
    craftStoryEn: "Luxurious Lucknowi Zardozi hand-embroidered clutch on raw silk base. Gold and silver metallic thread work with seed pearl and sequin detailing.",
    craftStoryHi: "लखनऊ की ज़रदोज़ी कढ़ाई से सजा रॉ सिल्क का शानदार क्लच पर्स। सोने-चाँदी के धातु के धागों और मोतियों की सजावट।",
    materialsEn: ["Raw Silk", "Gold Metallic Thread", "Seed Pearls", "Sequins"],
    materialsHi: ["रॉ सिल्क", "सोने का धातु धागा", "छोटे मोती", "सितारे"],
    dimensions: "25cm x 15cm x 5cm",
    weight: "0.18 kg",
    image: "https://images.unsplash.com/photo-1594633313593-bab3825d0caf?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 650,
      laborHours: 20,
      laborHourlyRate: 100,
      complexityGrade: 5,
      artisanExperienceYears: 15,
      demandIndex: 1.4,
      minimumFairPrice: 2650,
      suggestedB2BPrice: 3800,
    },
    status: "published",
    createdAt: "2026-08-12",
    qrCodeId: "QR-KGX-116",
  },
];

export const sampleVoiceTranscripts = {
  en: "I made this handicraft using natural clay from Bankura riverbank. I worked on the hand wheel for 4 hours and fired it in the wood kiln for 10 hours. The raw clay and firewood cost around 280 rupees. It is 35 centimeters high and weighs 1.4 kilograms.",
  hi: "ये बाँस की टोकरी है। इसे बनाने में लगभग दो दिन लगते हैं। इसमें बाँस और सूत का इस्तेमाल होता है। हम तीन लोग मिलकर इसे बनाते हैं। इसे हाथ से बुनते हैं। इसका आकार लगभग बारह इंच है।",
};
