import { ArtisanProfile, CraftCategory, ProductItem } from "./types";

export const initialArtisanProfile: ArtisanProfile = {
  id: "ART-808",
  name: "Ramesh Swarnakar",
  craftSpecialtyEn: "Terracotta & Heritage Pottery",
  craftSpecialtyHi: "टेराकोटा और पारंपरिक मिट्टी के बर्तन",
  locationEn: "Bankura, West Bengal",
  locationHi: "बांकुड़ा, पश्चिम बंगाल",
  experienceYears: 22,
  verificationBadge: "Pahchan Artisan Card #WB-808",
  avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80",
  totalProducts: 14,
  totalEarningsInr: 48500,
};

export const craftCategories: CraftCategory[] = [
  {
    id: "terracotta",
    nameEn: "Terracotta & Clay",
    nameHi: "टेराकोटा और मिट्टी",
    iconName: "Flame",
    descriptionEn: "Traditional baked clay horses, pots, figurines & tiles",
    descriptionHi: "पारंपरिक मिट्टी के घोड़े, बर्तन, मूर्तियां और टाइलें",
    color: "bg-orange-500/10 text-orange-700 border-orange-200",
    sampleImage: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "pottery",
    nameEn: "Blue Pottery & Ceramics",
    nameHi: "ब्लू पॉटरी और सिरेमिक",
    iconName: "Sparkles",
    descriptionEn: "Quartz-glazed Jaipur blue pottery, vases & tableware",
    descriptionHi: "जयपुर की प्रसिद्ध ब्लू पॉटरी, फूलदान और सजावटी बर्तन",
    color: "bg-sky-500/10 text-sky-700 border-sky-200",
    sampleImage: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "brass",
    nameEn: "Dhokra & Brass Craft",
    nameHi: "ढोकरा और पीतल कला",
    iconName: "Hammer",
    descriptionEn: "Lost-wax bell metal casting, brass lamps & tribal art",
    descriptionHi: "पारंपरिक पीतल के दिए, घंटियां और ढोकरा जनजातीय कला",
    color: "bg-amber-500/10 text-amber-700 border-amber-200",
    sampleImage: "https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "woodwork",
    nameEn: "Carved Woodwork",
    nameHi: "लकड़ी पर नक्काशी",
    iconName: "Trees",
    descriptionEn: "Saharanpur carved teakwood panels, boxes & toys",
    descriptionHi: "सहारनपुर की सागौन की लकड़ी की नक्काशीदार डिब्बे व खिलौने",
    color: "bg-emerald-500/10 text-emerald-700 border-emerald-200",
    sampleImage: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "textiles",
    nameEn: "Handloom Textiles",
    nameHi: "हथकरघा वस्त्र व साड़ियां",
    iconName: "Shirt",
    descriptionEn: "Handwoven Ikat, Chanderi, Pashmina & Zardozi embroidery",
    descriptionHi: "हाथ से बुनी इकत, चंदेरी, पश्मीना व ज़रदोज़ी कढ़ाई",
    color: "bg-rose-500/10 text-rose-700 border-rose-200",
    sampleImage: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "paintings",
    nameEn: "Folk Paintings",
    nameHi: "लोक चित्रकला (मधुबनी/वरली)",
    iconName: "Palette",
    descriptionEn: "Madhubani, Warli, Pattachitra & Gond folk wall art",
    descriptionHi: "मधुबनी, वरली, पट्टचित्र और गोंड लोक कला पेंटिंग",
    color: "bg-purple-500/10 text-purple-700 border-purple-200",
    sampleImage: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=400&q=80",
  },
];

export const initialProducts: ProductItem[] = [
  {
    id: "PRD-101",
    titleEn: "Heritage Bankura Terracotta Horse (35cm)",
    titleHi: "पारंपरिक बांकुड़ा टेराकोटा घोड़ा (35 सेमी)",
    category: "terracotta",
    categoryNameEn: "Terracotta & Clay",
    categoryNameHi: "टेराकोटा और मिट्टी",
    craftStoryEn: "Handcrafted using alluvial riverbank clay from Bankura. Molded by hand wheel and baked in a natural firewood kiln for 14 hours. Represents traditional Panchmura artisan heritage.",
    craftStoryHi: "बांकुड़ा की नदी की मिट्टी से हाथ से बनाया गया। 14 घंटे प्राकृतिक लकड़ी के भट्ठे में पकाया गया। यह पंचमुरा कारीगरों की सांस्कृतिक विरासत है।",
    materialsEn: ["Alluvial River Clay", "Natural Earth Ochre Pigment"],
    materialsHi: ["नदी की प्राकृतिक मिट्टी", "प्राकृतिक गेरू रंग"],
    dimensions: "35cm x 15cm x 10cm",
    weight: "1.4 kg",
    image: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 280,
      laborHours: 14,
      laborHourlyRate: 90,
      complexityGrade: 4,
      artisanExperienceYears: 22,
      demandIndex: 1.25,
      minimumFairPrice: 1540,
      suggestedB2BPrice: 2250,
    },
    status: "published",
    createdAt: "2026-09-01",
    qrCodeId: "QR-KGX-101",
    voiceTranscriptEn: "This is a 35cm high Bankura terracotta horse. It took me 14 hours of work and 280 rupees of raw clay and wood for firing.",
    voiceTranscriptHi: "यह 35 सेमी ऊँचा बांकुड़ा का मिट्टी का घोड़ा है। इसे बनाने में 14 घंटे की मेहनत लगी और 280 रुपये का सामान लगा।",
  },
  {
    id: "PRD-102",
    titleEn: "Jaipur Floral Blue Pottery Vase",
    titleHi: "जयपुर फूलदार नीला सिरेमिक फूलदान",
    category: "pottery",
    categoryNameEn: "Blue Pottery",
    categoryNameHi: "ब्लू पॉटरी",
    craftStoryEn: "Authentic quartz-based Jaipur blue pottery vase decorated with cobalt oxides and hand-painted traditional Mughal floral motifs.",
    craftStoryHi: "क्वार्ट्ज और कोबाल्ट ऑक्साइड से निर्मित प्रामाणिक जयपुर ब्लू पॉटरी फूलदान, हाथ से चित्रित पारंपरिक मुगल पैटर्न।",
    materialsEn: ["Quartz Powder", "Glass Frit", "Cobalt Oxide Dye"],
    materialsHi: ["क्वार्ट्ज पाउडर", "कांच का चूर्ण", "कोबाल्ट रंग"],
    dimensions: "28cm x 12cm",
    weight: "0.9 kg",
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 350,
      laborHours: 16,
      laborHourlyRate: 100,
      complexityGrade: 5,
      artisanExperienceYears: 18,
      demandIndex: 1.3,
      minimumFairPrice: 1950,
      suggestedB2BPrice: 2800,
    },
    status: "published",
    createdAt: "2026-08-28",
    qrCodeId: "QR-KGX-102",
  },
  {
    id: "PRD-103",
    titleEn: "Dhokra Bell Metal Peacock Lamp",
    titleHi: "ढोकरा पीतल मयूर दीया",
    category: "brass",
    categoryNameEn: "Dhokra Craft",
    categoryNameHi: "ढोकरा कला",
    craftStoryEn: "Traditional lost-wax brass casting crafted by tribal artisans in Bastar. Features intricate hand-spun wax wirework detailing.",
    craftStoryHi: "बस्तर के जनजातीय कारीगरों द्वारा प्राचीन लॉस्ट-वैक्स विधि से तैयार किया गया पीतल का सजावटी दीया।",
    materialsEn: ["Recycled Brass", "Bee Wax", "Clay Core"],
    materialsHi: ["पीतल धातु", "मोम की तार", "मिट्टी"],
    dimensions: "20cm x 15cm",
    weight: "1.1 kg",
    image: "https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 450,
      laborHours: 18,
      laborHourlyRate: 110,
      complexityGrade: 5,
      artisanExperienceYears: 20,
      demandIndex: 1.35,
      minimumFairPrice: 2430,
      suggestedB2BPrice: 3400,
    },
    status: "published",
    createdAt: "2026-08-25",
    qrCodeId: "QR-KGX-103",
  },
  {
    id: "PRD-104",
    titleEn: "Hand-Carved Saharanpur Teak Jewelry Box",
    titleHi: "सहारनपुर नक्काशीदार लकड़ी का गहना डिब्बा",
    category: "woodwork",
    categoryNameEn: "Carved Woodwork",
    categoryNameHi: "लकड़ी की नक्काशी",
    craftStoryEn: "Solid seasoned teakwood jewelry box intricately carved with traditional leaf brass inlay work.",
    craftStoryHi: "ठोस सागौन की लकड़ी से बना गहनों का डिब्बा, जिस पर पीतल के तारों और नक्काशी की सजावट की गई है।",
    materialsEn: ["Seasoned Teakwood", "Brass Wire Inlay"],
    materialsHi: ["सागौन की लकड़ी", "पीतल का काम"],
    dimensions: "22cm x 14cm x 8cm",
    weight: "0.8 kg",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80",
    pricing: {
      rawMaterialCost: 320,
      laborHours: 10,
      laborHourlyRate: 90,
      complexityGrade: 3,
      artisanExperienceYears: 15,
      demandIndex: 1.15,
      minimumFairPrice: 1220,
      suggestedB2BPrice: 1850,
    },
    status: "draft",
    createdAt: "2026-09-02",
    qrCodeId: "QR-KGX-104",
  },
];

export const sampleVoiceTranscripts = {
  en: "I made this handicraft using natural clay from Bankura riverbank. I worked on the hand wheel for 4 hours and fired it in the wood kiln for 10 hours. The raw clay and firewood cost around 280 rupees. It is 35 centimeters high and weighs 1.4 kilograms.",
  hi: "मैंने यह बांकुड़ा की नदी की प्राकृतिक मिट्टी से बनाया है। चाक पर 4 घंटे काम किया और भट्ठे में 10 घंटे पकाया। मिट्टी और लकड़ी का खर्चा 280 रुपये आया। यह 35 सेमी ऊँचा है और 1.4 किलो का है।",
};
